name: Build Docker image and push

on:
  workflow_call:
    inputs:
      runs-on:
        required: true
        description: Platform to execute on
        type: string

      aws_account_id:
        required: true
        description: Destination AWS Account
        type: string

      aws_region:
        required: false
        description: Destination AWS region
        type: string
        default: us-west-2

      file:
        required: false
        type: string
        default: ./Dockerfile

      context:
        required: false
        type: string
        default: ./

      environment:
        required: true
        type: string

      repository:
        required: false
        default: ${{ github.event.repository.name }}
        type: string

    secrets:
      NPM_TOKEN:
        required: false

    outputs:
      version:
        description: Docker image tag.
        value: ${{ jobs.deploy-to-ecr.outputs.version }}

jobs:
  deploy-to-ecr:
    name: Build docker image, push to ECR.
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ inputs.aws_account_id }}:role/github
          role-session-name: ${{ github.event.repository.name }}
          aws-region: ${{ inputs.aws_region }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Process version
        id: version
        run: |
          echo "version=${{ inputs.environment }}-${{ github.run_attempt}}-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push docker image (private repo)
        uses: docker/build-push-action@v3
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.file }}
          push: true
          no-cache: true
          build-args: |
            NPM_TOKEN=${{ secrets.NPM_TOKEN }}
            ENV_FILE_NAME=${{ inputs.environment }}
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ inputs.repository }}:${{ steps.version.outputs.version }}

