name: Build Docker image and push

on:
  workflow_call:
    inputs:
      runs-on:
        required: true
        description: 'Platform to execute on. Default ["self-hosted", "cere-io-large-workers"]'
        type: string
        default: '["self-hosted", "cere-io-large"]'

      aws_account_id:
        required: true
        description: Destination AWS Account
        type: string

      aws_region:
        required: false
        description: "Destination AWS region. Default us-west-2"
        type: string
        default: 'us-west-2'

      file:
        required: false
        description: "Path to the Dockerfile. Default: ./Dockerfile"
        type: string
        default: './Dockerfile'

      context:
        required: false
        description: "Build's context. Defaults ./"
        type: string
        default: './'

      environment:
        required: true
        description: "Build environment, effects image tag prefix. Default dev"
        type: string
        default: 'dev'

      repository:
        required: false
        description: "Image repository. Defaults to github repository name."
        type: string
        default: ${{ github.event.repository.name }}

    secrets:
      NPM_TOKEN:
        required: false

    outputs:
      version:
        description: Docker image tag.
        value: ${{ jobs.deploy-to-ecr.outputs.version }}

jobs:
  deploy-to-ecr:
    name: Build docker image, push to ECR.
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ inputs.aws_account_id }}:role/github
          role-session-name: ${{ github.event.repository.name }}
          aws-region: ${{ inputs.aws_region }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Process version
        run: |
          echo "image_tag=${{ inputs.environment }}-${{ github.run_attempt}}-$(git rev-parse --short HEAD)" >> "$GITHUB_ENV"

      - name: Build and push docker image to ECR
        uses: docker/build-push-action@v3
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.file }}
          push: true
          no-cache: true
          build-args: |
            NPM_TOKEN=${{ secrets.NPM_TOKEN }}
            ENV_FILE_NAME=${{ inputs.environment }}
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ inputs.repository }}:${{ env.image_tag }}

    outputs:
      version: ${{ env.image_tag }}
