name: Release service with helm.

on:
  workflow_call:
    inputs:
      runs-on:
        required: true
        description: Platform to execute on
        type: string

      helm-repo-path:
        required: true
        type: string
      helm-release:
        required: true
        type: string

      namespace:
        required: true
        type: string

      tag:
        required: true
        type: string
      first-tag-name:
        required: false
        type: string
        default: image.tag
      second-tag-name:
        required: false
        type: string
        default: global.image.tag
      environment:
        required: true
        type: string

    secrets:
      TRIGGER_GITHUB_TOKEN:
        required: true
      HELM_VERSION:
        required: true
      KUBECTL_VERSION:
        required: true
      K8S_DEPLOYMENT_CONFIGS_REPOSITORY:
        required: true

jobs:
  deploy:
    name: Upgrade service with helm.
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ secrets.K8S_DEPLOYMENT_CONFIGS_REPOSITORY }}
          token: ${{ secrets.TRIGGER_GITHUB_TOKEN }}
      - uses: azure/setup-helm@v1
        with:
          version: ${{ secrets.HELM_VERSION }}
      - uses: azure/setup-kubectl@v1
        with:
          version: ${{ secrets.KUBECTL_VERSION }}
      - name: Deploy
        env:
          HELM_RELEASE: ${{ inputs.helm-release }}
          HELM_REPO_PATH: ${{ inputs.helm-repo-path }}
          NAMESPACE: ${{ inputs.namespace }}
          ENVIRONMENT: ${{ inputs.environment }}
          TAG: ${{ inputs.tag }}
          FIRST_TAG_NAME: ${{ inputs.first-tag-name }}
          SECOND_TAG_NAME: ${{ inputs.second-tag-name }}
        run: |
          helm upgrade --install ${HELM_RELEASE} ${HELM_REPO_PATH} \
            -f ${HELM_REPO_PATH}/envs/${ENVIRONMENT}.yaml \
            --set ${FIRST_TAG_NAME}=${TAG} \
            --set ${SECOND_TAG_NAME}=${TAG} \
            --debug --atomic --cleanup-on-fail \
            --timeout 10m \
            -n ${NAMESPACE}
